### PR TITLE
Viem Example

### PR DESCRIPTION
**Pull request by 0xClouds**
Adds a frontend example using viem and viem account abstraction extension to sponsor a transaction.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by chunter-cb — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for chunter-cb @ 2024-10-24 20:09:30 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by chunter-cb — APPROVED** [review]

**Review by chunter-cb — APPROVED** [review]

**Comment by cb-heimdall** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/paymaster-bundler-examples/issues/42) to review and +1

**Review by qsadyysy786-tech — COMMENTED** [review]
- [ ]

**Review by qsadyysy786-tech — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for qsadyysy786-tech @ 2026-03-07 21:16:15 UTC
User failed mfa authentication, either user does not exist or public email is not set on your github profile. `\
        `see [go/mfa-help](http://go/mfa-help)

**Comment by qsadyysy786-tech** [comment]
- [x]

**Pull request merged**
