### PR TITLE
Update config.js

### PR DESCRIPTION
**Pull request by Herand19**

### CODE REVIEW

**Review by Bagin110 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Bagin110 @ 2024-04-14 20:38:56 UTC
User must have write permissions to review

**Review by Herand19 — COMMENTED** [review]
.

**Review by Bagin110 — COMMENTED** [review]
Dontrun

**Review by Herand19 — COMMENTED** [review]
.

**Review by Herand19 — COMMENTED** [review]
.

**Pull request closed without merging**
